A = imread('../images/4.1.01.tiff');
myClass = UtilityFunctions;
P1 =  myClass.getConsumption(A);
B = A(:,:, 3);
B = B - 100;
C = A
C(:,:, 3) = B;
P2 = myClass.distortion(A, C);
Power1 = P1
Power2 = P2
